name: crypt
version: 1.0.2
description: One-way string hashing for salted passwords using the Unix crypt format
homepage: https://github.com/hoylen/dart-crypt
author: Hoylen Sue <hoylen@hoylen.com>
environment:
  sdk: ">=1.13.0 <2.0.0"
dev_dependencies:
  test: "^0.12.10"
dependencies:
  crypto: ">=0.9.0 <2.0.0" # Note: until they get upgraded, this needs to co-exist with packages that depend on 0.x.x versions
