name: crypt
version: 0.0.2
description: One-way string hashing for salted passwords
homepage: https://github.com/hoylen/dart-crypt
author: Hoylen Sue <hoylen@hoylen.com>
dependencies:
  crypto: "^1.0.0"
dev_dependencies:
  unittest: any
